version: "3.8"
services:
  #database
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #django application
  app: #this is the name of the image....in this case app
  # build is that the Dockerfile is in the same folder
    build: .
  # this specify the link between containers and other
    volumes:
      - .:/taiprm_altai #this is the link between folders (if something change locali will later on be applied to the container)
    environment:
      - SECRET_KEY=eduardosecretkey
      - DEBUG=1
    ports:
      - 8000:8000 #expose from 8000 in our computer to the other port in the image
    image: app:taiprm_altai
    container_name: taiprm_altia_container
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  #  environment:
  #    - DEBUG=1 # change to 0 in a deployment server

  #redis
  redis:
    image: redis
    container_name: redis

  #celery
#  celery:
#    restart: always
#    build:
#      context: .
#    command: celery -A core worker -l INFO
#    volumes:
#      - .:/django
#    container_name: celery
#    depends_on:
#      - db
#      - redis
#      - app