# Generated by Django 3.2.15 on 2022-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A5Q12_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A5Q26_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A5Q28_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q19',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q19_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q20',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q20_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q21',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q21_2',
        ),
        migrations.AddField(
            model_name='assessment',
            name='A2Q46',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q11',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q12',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q13',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q18',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q20',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q22',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q23',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q24',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q26',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q8',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q10',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q11',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q15',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q19',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q20',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q24',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q25',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q29',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q30',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q31',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q32',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q33',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q34',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q35',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q36',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q37',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q38',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q39',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q40',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q41',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q42',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q43',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q44',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q45',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q7',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q9',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q9',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q11',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q12',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q7',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q9',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q12',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q17',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q26',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q28',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q29',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q31',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q12',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q14',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q15',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q16',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q17',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q18',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q7',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q8',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q14',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q3',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q10_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q12_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q13_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q14_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q2_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q3_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q4_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q5_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q6_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q7_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q8_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q9_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
    ]
