# Generated by Django 3.2.15 on 2022-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0002_auto_20220930_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='A1Q12',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q13',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q23',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q24',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q10',
            field=models.CharField(choices=[('5', 'Non-existent'), ('4', 'Low'), ('3', 'Moderate'), ('2', 'Significant'), ('1', 'High')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q11',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q20',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q30',
            field=models.CharField(choices=[('0', 'Yes'), ('1', 'No'), ('2', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q32',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
