# Generated by Django 3.2.15 on 2022-09-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0003_auto_20220930_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q11_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q18_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q20_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q22_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q26_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q8_2',
        ),
    ]
