# Generated by Django 3.2.15 on 2022-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0004_auto_20220930_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q15_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A1Q16_2',
        ),
        migrations.AddField(
            model_name='assessment',
            name='A2Q46_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
    ]
