# Generated by Django 3.2.15 on 2022-09-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0005_auto_20220930_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A4Q11_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A4Q3_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A4Q7_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A4Q9_2',
        ),
    ]
