# Generated by Django 3.2.15 on 2022-09-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0006_auto_20220930_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q15_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q2_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q4_2',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q6_2',
        ),
    ]
