# Generated by Django 3.2.15 on 2022-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0007_auto_20220930_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A6Q12_2',
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations1',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations2',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations3',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations4',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations5',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations6',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='recommendations7',
            field=models.CharField(blank=True, default='[]', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q14',
            field=models.CharField(choices=[('Impossibl', 'Impossible'), ('Unlikely', 'Unlikely'), ('Possible', 'Possible'), ('Likely', 'Likely')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q15',
            field=models.CharField(choices=[('Impossibl', 'Impossible'), ('Unlikely', 'Unlikely'), ('Possible', 'Possible'), ('Likely', 'Likely')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q16',
            field=models.CharField(choices=[('Impossibl', 'Impossible'), ('Unlikely', 'Unlikely'), ('Possible', 'Possible'), ('Likely', 'Likely')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q17',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q19',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q21',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q27',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q28',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q12',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q13',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q14',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q16',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q17',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q18',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q19',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q21',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q22',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q23',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q26',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q27',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q28',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q29',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q30',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q33',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q34',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q35',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q36',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q37',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q38',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q39',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q40',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q41',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q11',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q13',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q14',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q15',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q16',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q18',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q19',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q20',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q21',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q22',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q23',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q24',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q25',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q27',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not applicable', 'Not applicable')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q30',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q11',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q13',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q14',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q16',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q11',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q12',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q13',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q7',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q8',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A7Q9',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
    ]
