# Generated by Django 3.2.15 on 2022-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0008_auto_20220930_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='A1Q29',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q29_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q30',
            field=models.CharField(choices=[('Abort the process entirely', 'Abort the process entirely'), ('Abort the process in part', 'Abort the process in part'), ('Delegate control to a human', 'Delegate control to a human'), ('Other', 'Other'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q30_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q31',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Do not know', 'Do not know')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q31_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q32',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A1Q32_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
    ]
