# Generated by Django 3.2.15 on 2022-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0010_auto_20221003_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='A4Q5_2',
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q11_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q13',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q14',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q14_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q15',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q16',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q16_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q17',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q18',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A4Q18_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q10',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q11',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q12',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q6',
            field=models.CharField(choices=[('Yes', 'Yes'), ('To Some extent', 'To Some extent'), ('No', 'No'), ("Don't know", "Don't know")], default='Unspecified', max_length=100, null=True),
        ),
    ]
