# Generated by Django 3.2.15 on 2022-10-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0011_auto_20221003_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='A6Q19',
            field=models.CharField(choices=[('1', 'Non-existent'), ('2', 'Completely inadequate'), ('3', 'Almost adequate'), ('4', 'Adequate'), ('5', 'Fully adequate')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A6Q19_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='A6Q20',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
