# Generated by Django 3.2.15 on 2022-10-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0012_auto_20221003_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='T3Q15_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T3Q16',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='ramarkscriticality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='ramarksfailuremode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='T3Q15',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
    ]
