# Generated by Django 3.2.15 on 2022-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0013_auto_20221018_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failuremode',
            name='D',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='O',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='RPN',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='S',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='alpha',
        ),
        migrations.AddField(
            model_name='taiprm',
            name='IDfailure',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='KPIprevious',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='LinkedID',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='actionsrecommended',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='actionsresponsible',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='actionstaken',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='beta',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='comments',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='cr',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='description',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='detectiondescription',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='detectionmethod',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='failurecauses',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='failureprobabilitysource',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='gama',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='globaleffect',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='item',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='itemcausing',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='localeffect',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='mode',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='operatingtime',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='ramarkscriticality',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='ramarksfailuremode',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='severityclass',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='subsystem',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='system',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='systemstatusatfailing',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.DeleteModel(
            name='SOD',
        ),
    ]
