# Generated by Django 3.2.15 on 2022-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0014_auto_20221018_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='T9Q5',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T9Q5_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
    ]
