# Generated by Django 3.2.15 on 2022-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0016_taiprm_rpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='GRPN',
            field=models.TextField(default='[]', null=True),
        ),
    ]
