# Generated by Django 3.2.15 on 2022-10-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0017_taiprm_grpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='status9',
            field=models.BooleanField(default=False),
        ),
    ]
