# Generated by Django 3.2.15 on 2022-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0018_taiprm_status9'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='T11Q1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q1_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q3',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q3_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q4',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q4_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T11Q5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
