# Generated by Django 3.2.15 on 2022-10-31 16:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0019_auto_20221019_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failuremode',
            name='IDfailure',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='KPIprevious',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='LinkedID',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='actionsrecommended',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='actionsresponsible',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='actionstaken',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='detectiondescription',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='detectionmethod',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='failurecauses',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='failureprobabilitysource',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='gama',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='globaleffect',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='item',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='itemcausing',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='localeffect',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='operatingtime',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='ramarkscriticality',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='ramarksfailuremode',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='severityclass',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='subsystem',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='system',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='systemstatusatfailing',
        ),
        migrations.AddField(
            model_name='assessment',
            name='User_Information',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI Developer', 'AI Developer'), ('AI Architect', 'AI Architect'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Academy', 'Academy'), ('AI User', 'AI User'), ('Project Management', 'Project Management'), ('Media', 'Media'), ('Law Enforcement', 'Law Enforcement'), ('Other', 'Other')], max_length=142, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='User_Information',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI Developer', 'AI Developer'), ('AI Architect', 'AI Architect'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Academy', 'Academy'), ('AI User', 'AI User'), ('Project Management', 'Project Management'), ('Media', 'Media'), ('Law Enforcement', 'Law Enforcement'), ('Other', 'Other')], max_length=142, null=True),
        ),
    ]
