# Generated by Django 3.2.15 on 2022-10-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0020_auto_20221031_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failuremode',
            name='selected',
        ),
    ]
