# Generated by Django 4.1.3 on 2022-11-08 13:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0022_auto_20221107_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='A1Q25',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Is a self-learning or autnomous system'), (2, 'Is overseen by a human-in-the-loop'), (3, 'Is overseen by a human-in-the-loop'), (4, 'Is overseen by a human-in-command'), (5, 'other'), (6, 'Do not know')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A3Q4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Data Protection Impact Assessment'), (2, 'Designate a Data Protection Officer (DPO) and include him/her at an early stage in the development, procurement or use phase of the AI system'), (3, 'Oversight mechanisms for data processing (incl. limited access by qualified organisation members, mechanisms for logging data access and modifications)'), (4, ' Measures to enhance privacy by design and default (e.g., =gb=encryption, pseudonymisation, aggregation, anonymisation=ge=) '), (5, 'Data minimisation, in particular personal data (incl. special categories of data)')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='User_Information',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI Developer', 'AI Developer'), ('AI Architect', 'AI Architect'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Academy', 'Academy'), ('AI User', 'AI User'), ('Project Management', 'Project Management'), ('Media', 'Media'), ('Law Enforcement', 'Law Enforcement'), ('Other', 'Other')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='User_Information',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AI Developer', 'AI Developer'), ('AI Architect', 'AI Architect'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Academy', 'Academy'), ('AI User', 'AI User'), ('Project Management', 'Project Management'), ('Media', 'Media'), ('Law Enforcement', 'Law Enforcement'), ('Other', 'Other')], max_length=1000, null=True),
        ),
    ]
