# Generated by Django 4.1.3 on 2022-11-14 15:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0024_alter_assessment_a1q1_alter_assessment_a1q10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='T3Q17',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tabular', 'Tabular'), ('Image', 'Image'), ('Text', 'Text'), ('Natural Lenguage', 'Natural Lenguage')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='T3Q17_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='Unspecified', max_length=100, null=True),
        ),
    ]
