# Generated by Django 4.1.3 on 2022-11-14 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0026_taiprm_r1_1_taiprm_r1_2_taiprm_r1_3_taiprm_r2_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='altai',
            field=models.TextField(default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R1_1',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R1_2',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R1_3',
            field=models.IntegerField(default=1000, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R2_1',
            field=models.IntegerField(default=200, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R2_2',
            field=models.IntegerField(default=800, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R2_3',
            field=models.IntegerField(default=1000, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R3_1',
            field=models.IntegerField(default=400, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R3_2',
            field=models.IntegerField(default=1000, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R3_3',
            field=models.IntegerField(default=1000, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R4_1',
            field=models.IntegerField(default=800, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R4_2',
            field=models.IntegerField(default=1000, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R4_3',
            field=models.IntegerField(default=1000, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
