# Generated by Django 4.1.3 on 2022-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0027_taiprm_altai_alter_taiprm_r1_1_alter_taiprm_r1_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='R1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='R2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='R3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='R4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='R5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='R6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='R7',
            field=models.TextField(blank=True, null=True),
        ),
    ]
