# Generated by Django 4.1.3 on 2022-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0028_taiprm_r1_taiprm_r2_taiprm_r3_taiprm_r4_taiprm_r5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taiprm',
            name='R1',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R2',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R3',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R4',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R5',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R6',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='R7',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
