# Generated by Django 4.1.3 on 2022-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0029_alter_taiprm_r1_alter_taiprm_r2_alter_taiprm_r3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='porcentage',
            field=models.TextField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='taiprm',
            name='porcentage',
            field=models.TextField(default='0', null=True),
        ),
    ]
