# Generated by Django 4.1.3 on 2022-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0030_assessment_porcentage_taiprm_porcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taiprm',
            name='action',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q11',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q18',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q20',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q22',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q26',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A1Q8',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q15',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A2Q9',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q13',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q15',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q17',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q7',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A4Q9',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q12',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q26',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A5Q28',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q12',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q15',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q20',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='A6Q6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taiprm',
            name='porcentage',
            field=models.TextField(default='', null=True),
        ),
    ]
