# Generated by Django 4.1.3 on 2022-11-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0031_taiprm_action_alter_assessment_a1q11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taiprm',
            name='R1_1',
        ),
        migrations.RemoveField(
            model_name='taiprm',
            name='R1_2',
        ),
        migrations.RemoveField(
            model_name='taiprm',
            name='R1_3',
        ),
    ]
