# Generated by Django 4.1.3 on 2022-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altai_web', '0032_remove_taiprm_r1_1_remove_taiprm_r1_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuremode',
            name='failuremodefamily',
            field=models.CharField(choices=[('Technical Robustness', 'Technical Robustness'), ('Safety', 'Safety'), ('Transparency', 'Transparency'), ('Accountability', 'Accountability'), ('Societal Wellbeing', 'Societal Wellbeing'), ('Environmental Wellbeing', 'Environmental Wellbeing'), ('Human Agency and Oversight', 'Human Agency and Oversight'), ('Privacy', 'Privacy'), ('Data Governance', 'Data Governance'), ('Diversity,non-discrimination, and fairness', 'diversity,non-discrimination, and fairness'), ('Users Values', 'Users Values'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
